import os
from google.adk.agents import Agent
from skills.create_report import create_report

def get_report_agent() -> Agent:
    """
    Creates and returns the Report Agent.
    This agent compiles data metrics, quality metrics, and business insights
    into a professional, downloadable Markdown business report using create_report.
    """
    model_name = os.environ.get("GEMINI_MODEL", "gemini-2.5-flash")
    
    return Agent(
        name="report_agent",
        model=model_name,
        instruction=(
            "You are an Executive Report Agent. "
            "Your role is to write and save the final report. "
            "You MUST call the create_report tool. "
            "Make sure to pass all the required inputs to create_report: "
            "- clean_summary: Dict/Object from the data cleaning step. "
            "- insights_data: Dict/Object from the insights step (which includes quantitative metrics). "
            "- gemini_insights: The qualitative strategic text generated by the Insight Agent. "
            "Once the tool has executed, provide a brief summary confirmation. "
            "Confirm that the report was written to reports/business_report.md. "
            "Print the full compiled report text in markdown format so it can be shown directly to the user."
        ),
        tools=[create_report]
    )
